create table t_post (
    id int8 generated by default as identity,
    title varchar(255) not null,
    text varchar(2048) not null,
    user_id int8 not null,
    primary key (id)
);
create table t_role (
    id int8 not null,
    name varchar(255) not null,
    primary key (id)
);
create table t_user (
    id int8 generated by default as identity,
    username varchar(20) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    primary key (id)
);
create table t_user_roles (
    user_id int8 not null,
    roles_id int8 not null,
    primary key (user_id, roles_id)
);
alter table if exists t_post
    add constraint t_post_user_fk foreign key (user_id) references t_user;
alter table if exists t_user_roles
    add constraint t_role_fk foreign key (roles_id) references t_role;
alter table if exists t_user_roles
    add constraint t_user_fk foreign key (user_id) references t_user;